### ISSUE TITLE
Is it possible to have a second constructor for the Story object?

### ISSUE THREAD

**Issue by joedai** [bladecoder/blade-ink#10]
Currently `public Story(String jsonString)` takes in a JSON String, and the first thing this constructor does is calling `SimpleJson.textToHashMap(jsonString)` which has a huge impact on the performance when the JSON is big enough.

In our system, we have to create one story for each of our clients. Constructing the story object has taken up a lot of our processing time.

I am wondering if I can raise a PR and add a second constructor which looks like the following
`public Story(HashMap<String, Object> rootObject)`

Cheers.

**Comment by bladecoder** [comment]
Discussion in this PR: https://github.com/bladecoder/blade-ink/pull/12
