### ISSUE TITLE
External functions getting called twice

### ISSUE THREAD

**Issue by micabytes** [bladecoder/blade-ink#21]
Hi,

It is my understanding that with the new version of ink, external functions should only be called once (default behavior "actions", as opposed to the previous behavior where glue "lookahead" often caused functions to be called at any time, and frequently more than once).

However, when running external functions in blade-ink, I'm frequently seeing functions called twice.

I'm assuming this may be an issue in blade-ink, since I'm not seeing people complaining about this in ink issues. Thoughts?

Regards,

Michael A.

**Comment by BambooBandit** [comment]
I too am running into this problem. Have you resolved it somehow?

**Comment by BambooBandit** [comment]
It turns out this problem was on my end. i didn't use the bindExternalFunction function that had the lookaheadSafe parameter. I needed to pass in false and it only calls the functions once now!

**Comment by micabytes** [comment]
Keep an eye on it. There hasn't been a new version of Blade-Ink since (because there hasn't been a new Ink version), and I haven't really checked it since - I just stopped trusting Ink again on this point. The mix of Ink and code is complex enough that it's easier to work around the problem than to try and debug it.

But I've encountered times during debugging of other issues where it still seems to be doing this.

**Comment by amondnet** [comment]
https://github.com/bladecoder/blade-ink/blob/759a68138ebae5ca87246d4ca4089efbf9f97e1e/src/main/java/com/bladecoder/ink/runtime/Story.java#L344

	 * @param lookaheadSafe The ink engine often evaluates further than you might
	 *                      expect beyond the current line just in case it sees glue
	 *                      that will cause the two lines to become one. In this
	 *                      case it's possible that a function can appear to be
	 *                      called twice instead of just once, and earlier than you
	 *                      expect. If it's safe for your function to be called in
	 *                      this way (since the result and side effect of the
	 *                      function will not change), then you can pass 'true'.
	 *                      Usually, you want to pass 'false', especially if you
	 *                      want some action to be performed in game code when this
	 *                      function is called.


https://github.com/bladecoder/blade-ink/blob/759a68138ebae5ca87246d4ca4089efbf9f97e1e/src/main/java/com/bladecoder/ink/runtime/Story.java#L367

```java

	public void bindExternalFunction(String funcName, ExternalFunction<?> func) throws Exception {
		bindExternalFunction(funcName, func, true);
	}
```

**Comment by micabytes** [comment]
It took a while, but after tracking down all of the times I've reliably been able to reproduce this issue, I've concluded that it's either been the case of an issue like the above (i.e., using bindExternalFunction with the wrong parameters) or related to another bug in my code (as mentioned, I use a lot of custom code, and some of that also had issues).

After I had gone through every binding and fixed the bugs mentioned above, I no longer find this issue occuring.
