### ISSUE TITLE
Blade ink on Android Studio is not working

### ISSUE THREAD

**Issue by filipehaider** [bladecoder/blade-ink#22]
Hi friends, we are developing an app (Android Studio Artic Fox) that should read the story through a .json file generated by Inky . Blade ink is unable to recognize the characters in this file as shown in the message below. Could someone help us?

_W/System.err: java.lang.Exception: Unhandled RTObject type in JSON: ﻿{
      "inkVersion": 19,
      "ro
W/System.err:     at com.bladecoder.ink.runtime.SimpleJson$Reader.readObject(SimpleJson.java:171)
        at com.bladecoder.ink.runtime.SimpleJson$Reader.<init>(SimpleJson.java:40)
        at com.bladecoder.ink.runtime.SimpleJson.textToDictionary(SimpleJson.java:22)
        at com.bladecoder.ink.runtime.Story.<init>(Story.java:237)
        at br.ufjf.dcc196.filipehaider.prototipoapptcc.MainActivity.onCreate(MainActivity.java:48)_

**Comment by bladecoder** [comment]
The .json files generated by Inky have a BOM character at start, so, you need to delete it before to pass the string to the Story class. Here you have the method I use to read the .json file:

```

```

**Comment by filipehaider** [comment]
Thank you for your help. But now this error message appears, as if the .json file was not found.

_W/System.err: java.io.FileNotFoundException: ExemploPokemon.ink.json: open failed: ENOENT (No such file or directory)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)_


The **ExemploPokemon.ink.json** file is in the assets folder. And the code of the method you indicated was like this after adding the "try/catch":

        String json = null;
        try {
            json = getJsonString("ExemploPokemon.ink.json");
        } catch (IOException e) {
            e.printStackTrace();
        }
        try {
            story = new Story(json);
        } catch (Exception e) {
            e.printStackTrace();
        }
