### ISSUE TITLE
Incompatible versions of ink

### ISSUE THREAD

**Issue by BambooBandit** [bladecoder/blade-ink#23]
I tried making my own story with Inky, and tried it with the libgdx blade-ink-template, and got this error
`StoryManager: Cannot load Ink Story: story.ink.json Version of ink used to build story was newer than the current verison of the engine`

The template uses ink version "17", and my newly created one uses version "20"

I'm assuming I might need to download an older version of Inky, but when I look at their versions, none of them are 20, or 17, they are in decimal formats.

**Comment by BambooBandit** [comment]
My temporary solution was to download this older version of inky here https://github.com/inkle/inky/releases/tag/0.8.0

**Comment by JanSimek** [comment]
That's because blade-ink-template uses an older version of blade-ink. Open gradle.properties and change bladeInkVersion=0.4.4 to bladeInkVersion=1.0.0. That will make it compatible with the latest Inky.

**Comment by bladecoder** [comment]
I just updated the blade-ink-template project to work with the latest Blade Ink version. Now it works with the latest Inky.
