### ISSUE TITLE
GWT compatibility

### ISSUE THREAD

**Issue by czyzby** [bladecoder/blade-ink#3]
Although I've seen usage of some unsupported classes like `Thread`, it seems that it would be possible to make `blade-ink` compatible with LibGDX GWT backend. You would obviously have to rewrite some code and add a GWT module definition file, but HTML5/JS support might be worth the trouble.

**Comment by bladecoder** [comment]
I added the GWT module definition, it should work now with GWT but I have not tested it. Could you test the library with GWT for me?

Threads are not used in the library. There is an internal Thread class defined in the library, but it is a Ink concept not java a Java Thread.

**Comment by czyzby** [comment]
To be honest, I rarely do any LibGDX-related development nowadays. I'm sure you'll find some help on LibGDX IRC channel, though.
