### ISSUE TITLE
Exception when using threads to add choice points

### ISSUE THREAD

**Issue by danwilhelm** [bladecoder/blade-ink#5]
Great port! Noticed a slight incompatibility when experimenting with threads. 

For background, here is the ink documentation on implementing threads for choice points:  https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#example-organisation-of-wide-choice-points

**Expected result.** The below script should add an additional choice point to the 'start' knot, offering the user the additional choice of 'No'. If 'No' is selected, 'start' should be re-run.

**What happens.** When run with blade-ink, an exception is thrown (see below). When run with inklecate in interactive mode (`inklecate -p simple.ink`), the script runs correctly. I attempted different permutations of the script and the addition of gathers/etc, but the exception still occurs. 

**Simple script causing the exception.** 

```
-> start

=== start ===
Here is some gold. Do you want it?
- (top)
    <- choices(-> top)
    + Yes
        You win!
        -> END

=== choices(-> goback) ===
+ No
    Try again!
    -> goback
```

**Exception raised by blade-ink:**

`java.lang.Exception: RUNTIME ERROR: Variable 'goback' could not be found in context '-1'. This shouldn't be possible so is a bug in the ink engine. Please try to construct a minimal story that reproduces the problem and report to inkle, thank you!
    at com.bladecoder.ink.runtime.VariablesState.getRawVariableWithName(VariablesState.java:149)
    at com.bladecoder.ink.runtime.VariablesState.getVariableWithName(VariablesState.java:160)
    at com.bladecoder.ink.runtime.VariablesState.getVariableWithName(VariablesState.java:156)
    at com.bladecoder.ink.runtime.Story.performLogicAndFlowControl(Story.java:1086)
    at com.bladecoder.ink.runtime.Story.step(Story.java:1708)
    at com.bladecoder.ink.runtime.Story.continueInternal(Story.java:463)
    at com.bladecoder.ink.runtime.Story.Continue(Story.java:425)`

Thanks!

**Comment by bladecoder** [comment]
I try the test below in the latest version of blade-ink and it works well...

Can you tell me the inklecate version that are you using to compile and the blade-ink version?

Cheers!

**Comment by danwilhelm** [comment]
Thank you for the fast reply! I appreciate you taking the time to make a new test case. I verified that your test case works as intended.

It seems that I regrettably misattributed the error to the threading itself. Digging deeper, the exception is generated when converting threaded choice points to/from JSON. So, I will open a more specific issue which reuses the test script.

Because blade-ink works well with the issue above, I am closing this issue as resolved. Thanks again!
