### ISSUE TITLE
Premade libgdx harness for running a .ink file?

### ISSUE THREAD

**Issue by wohali** [bladecoder/blade-ink#9]
Hi there,

[Over here](https://github.com/inkle/ink/issues/248#issuecomment-271361812) you mentioned that you want to build out a template of a libgdx app as an example sometime.

I have a friend who really likes Ink, but is struggling to learn enough Unity to make a game. They don't want to use Twine because they want a desktop app that runs standalone, without a web browser engine involved. They are not programmers.

Is your project done? If so, could you post it somewhere? Getting a non-programmer from Ink to playable desktop game should be more straightforward than it is today, and I'm hoping blade-ink + libgdx might be a good alternative.

Thanks!

**Comment by bladecoder** [comment]
Hi!

I really want to make a libgdx template with basic functionality but I have not had time yet, sorry.

I want to create the template with only 2 features:

1. Menu Screen with some basic options: new game, continue, credits, help...
2. Play a configurable ink file. This includes an ui component to show/select choices.

**Comment by wohali** [comment]
That'd be perfect!

**Comment by micabytes** [comment]
I was recently experimenting with [TornadoFX](https://github.com/edvin/tornadofx) and mashed together a  simple desktop client for my mica-ink engine (previously jink).

Can be found [here](https://github.com/micabytes/storybytes-desktop). It's built in Kotlin with TornadoFX (a Kotlin wrapper around JavaFX). It'll run anything the mica-ink engine can handle; i.e., most simpler Ink scripts, but if necessary I expect it would not be terribly hard to rebuild it for the blade-ink engine. It's literally like 50 lines of code or something like that.

**Comment by bladecoder** [comment]
Finally I found the time to write a template to create Ink applications using libgdx!

It's called **Blade Ink Template** and is available [here](https://github.com/bladecoder/blade-ink-template).

Here you can see a video playing The Intercept game:  

https://youtu.be/NMbkduNAeeI

Any comment will be welcome!
